### ISSUE TITLE
为什么导入到intellij idea 里面, 配置好tomcat9 打开却是404呢

### ISSUE THREAD

**Issue by iroywang** [IcedSoul/Shopping#1]
<img width="1680" alt="2018-06-26 1 37 52" src="https://user-images.githubusercontent.com/24937504/41891302-4bdaf1c0-7946-11e8-8450-9485f9db87e5.png">
<img width="1680" alt="2018-06-26 1 37 59" src="https://user-images.githubusercontent.com/24937504/41891303-4c29d128-7946-11e8-9e9e-22e6eddcf5fd.png">
<img width="1680" alt="2018-06-26 1 38 01" src="https://user-images.githubusercontent.com/24937504/41891305-4c6f3524-7946-11e8-9403-e71c2e48e971.png">

**Comment by IcedSoul** [comment]
@iroywang 
我仔细看了一下你的配置，大概上应该是没有什么问题的，不过使用war:exploded有时候会出问题，我还不是很懂它和war的区别。我把我的配置信息截图，你参考一下。刚刚我在本地跑了一下，按照我的配置应该是可以正常运行的。
![1](https://user-images.githubusercontent.com/16553469/42074509-3eb7ded0-7b9f-11e8-80b4-e87cd70bda68.PNG)
![2](https://user-images.githubusercontent.com/16553469/42074510-3ef477dc-7b9f-11e8-8d36-dc6f6dcf27c4.PNG)
![3](https://user-images.githubusercontent.com/16553469/42074511-3f338e86-7b9f-11e8-82c8-5fa2545a2968.PNG)

**Comment by xsxdtc** [comment]
朋友你的问题解决了吗
