### ISSUE TITLE
我按照你的配置都配好了，但是运行的时候报了Failed to load class "org.slf4j.impl.StaticLoggerBinder". 

### ISSUE THREAD

**Issue by xsxdtc** [IcedSoul/Shopping#2]
![image](https://user-images.githubusercontent.com/30565274/47982551-25363700-e10b-11e8-8581-6ce14f56e6b4.png)
在pom。xml里添加了依赖还是不行，能帮我一下吗？谢谢🙏

**Comment by xsxdtc** [comment]
![image](https://user-images.githubusercontent.com/30565274/47990276-1c9d2b00-e122-11e8-9925-88ab9e5ed015.png)
![image](https://user-images.githubusercontent.com/30565274/47990285-21fa7580-e122-11e8-8942-9b496c5b4d49.png)
![image](https://user-images.githubusercontent.com/30565274/47990292-24f56600-e122-11e8-8ec9-f9cb5efb8fad.png)
![image](https://user-images.githubusercontent.com/30565274/47990327-38083600-e122-11e8-99f9-0b5824b840cc.png)
![image](https://user-images.githubusercontent.com/30565274/47990295-2757c000-e122-11e8-99cc-c806f187d86c.png)

**Comment by xsxdtc** [comment]
B3930D603480393BAD17D4C73D60D6A4.jpg

**Comment by xsxdtc** [comment]
![b3930d603480393bad17d4c73d60d6a4](https://user-images.githubusercontent.com/30565274/47993289-101cd080-e12a-11e8-9eca-b3bac7d9f46f.jpg)

**Comment by IcedSoul** [comment]
这个应该不是代码本身的问题，是你本地有一些依赖没有拉下来。可以尝试一下清楚一下自己本地的Maven仓库，然后重新mvn clean package 下载相关的依赖。

**Comment by IcedSoul** [comment]
配置是没有什么问题的。
