### ISSUE TITLE
为啥界面会报信息查询错误

### ISSUE THREAD

**Issue by xudong5273** [IcedSoul/Shopping#4]

**Comment by IcedSoul** [comment]
是在线演示，还是本地运行，具体是什么环境呢？  
如果是本地运行是否提前新建好数据库了？  
如果数据库没问题那么具体是在什么情况下，哪个页面点击什么按钮报错的，前端是否有什么报错信息，控制台是否有报错信息？如果有的话能否给出详细截图～

**Comment by xudong5273** [comment]
本地运行出错，你的mysql依赖是5.1，我的数据库是在本地电脑虚拟机docker部署的mysql5.6，是不是因为这个不兼容。tomcat日志报错误是连接出错

**Comment by IcedSoul** [comment]
5.1和5.6没什么区别，我用5.6也没问题。  
你用docker跑MySQL可能涉及到端口映射的问题，建议你使用navicat或者类似工具测试你的MySQL是否可以连接。

**Comment by xudong5273** [comment]
可以连接，但是报错了，现在我在公司搭建弄好了，谢谢大佬，问题因该是docker部署的数据库的原因，晚上我在搞搞。提几个我发现小问题，1.注册的时候性别男女都可以选择2.管理员居然能把自己删掉，这里的删除居然是物理删除。3.用户可对评价进行增删改查。这些都是小问题如果大佬没时间维护，我下面就接着大佬的维护了，谢谢大佬的抛砖引“玉”。最后谢谢大佬。在这里也说下我遇到的问题及解决方案，方便后面的小伙伴少走坑。tomcat启动项目报GBK不可编译。在pom文件设置编码格式为UTF-8即可。谢谢大佬。

**Comment by IcedSoul** [comment]
OK，你说的问题确实都存在233，但是因为是个练习用小项目所以这些功能上的问题我都没有改。如果你改掉欢迎提pull request。  
tomcat启动报错的问题我之前没有遇到过，不过设置一下编码问题不大，之后我会在pom中加上utf-8编码设置。
