### ISSUE TITLE
为什么总是显示查询错误，然后点什么都没有反应

### ISSUE THREAD

**Issue by yzsjy** [IcedSoul/Shopping#5]

**Comment by IcedSoul** [comment]
请参考 #4 ，如果还无法解决请描述详细情况。

**Comment by DXJ121** [comment]
也显示查询错误，其他地方都点不动

**Comment by IcedSoul** [comment]
> 也显示查询错误，其他地方都点不动
看上面一条回复，如果无法解决请提供详细信息。

**Comment by IcedSoul** [comment]
请参考上一条回答，仍未解决请提供详细信息。

**Comment by DXJ121** [comment]
> 请参考上一条回答，仍未解决请提供详细信息。

知道了  mysql版本高了  换一下mysql-connecter-java的版本就行了 供大家参考
