### ISSUE TITLE
管理员登录

### ISSUE THREAD

**Issue by DXJ121** [IcedSoul/Shopping#6]
如何进行管理员登录？  
将数据库中某用户的role字段改为1后 是在原来的登录界面登录？ 还是有特定的登录界面？

**Comment by IcedSoul** [comment]
role字段为1角色登陆后主页面会有进入管理员页面按钮。

**Comment by DXJ121** [comment]
> role字段为1角色登陆后主页面会有进入管理员页面按钮。

没看到。。。

**Comment by IcedSoul** [comment]
右上角，再看看。
