### ISSUE TITLE
浏览器乱码问题

### ISSUE THREAD

**Issue by Vincent-2018** [IcedSoul/Shopping#7]
创建数据库时选择utf-8，sql文本里省略create database...这条语句，用navicat运行脚本。
在database.properties里，url地址改成url=jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8
一定要加上?后面的参数，否则后期加入购物车后，商品库里的数据会乱码

**Comment by IcedSoul** [comment]
是的，这是数据库编码问题。自己新建时确实需要注意使用UTF-8。如果不选择UTF-8数据库存储中文时会出现乱码，后续我会在sql文件和jdbc url增加相关代码。
